### ISSUE TITLE
Request生成時、例外が返されるエラー

### ISSUE THREAD

**Issue by hsgw-yuta** [bolg-developers/sumimasen#1]

**Comment by hsgw-yuta** [comment]
UnsupportedOperationException()がthrowされる

**Comment by hsgw-yuta** [comment]
エラー表示
`09-28 17:59:12.348 18323-18323/com.example.bolg E/HAL: hw_get_module_by_class: lib loaded: /system/lib64/hw/gralloc.msm8952.so
09-28 17:59:13.236 18323-18347/com.example.bolg E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.example.bolg, PID: 18323
    java.lang.UnsupportedOperationException
        at bolg_developers.sumimasen.api.SumimasenRequest.dynamicMethod(SumimasenRequest.java:182)
        at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:325)
        at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:1475)
        at com.google.protobuf.GeneratedMessageLite.isInitialized(GeneratedMessageLite.java:251)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:421)
        at com.example.bolg.HelloService.greet(HelloGrpcTask.kt:17)
        at com.example.bolg.MainActivity$func$1$1.invokeSuspend(MainActivity.kt:30)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

**Comment by hsgw-yuta** [comment]
変えてみる
`            //stub.sumimasen(request)
            SumimasenResponse.newBuilder().setMessage(stub.sumimasen(request).message).build()
`
結果落ちました。

**Comment by hsgw-yuta** [comment]
`https://nekonenene.hatenablog.com/entry/android-grpc-client-with-kotlin`
のapp/buildgradleを参考に.ktで書いてみる

**Comment by hsgw-yuta** [comment]
新しく違う階層に再生成してみたが同じ現象になってしまった

**Comment by hsgw-yuta** [comment]
現状を書いておきます。
host: 172.20.10.8
port:50051

![ipconfig](https://user-images.githubusercontent.com/41692106/66711595-cae93000-edc9-11e9-9fdb-06ea1f239055.png)
![error](https://user-images.githubusercontent.com/41692106/66711596-d3416b00-edc9-11e9-90d5-45236e8505a2.png)


こんな感じのエラー
